apiVersion: v1
kind: Config
clusters:
  - name: dev
    cluster:
      server: https://10.24.17.161:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSTFtRXFPV2J4aUV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBME1qTXhNREk0TkRoYUZ3MHpOREEwTWpFeE1ETXpORGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN6ZFdBUkdPMEY2bGpsWEJkR1Z2RFMzbElCcG1Bd0VnM0lwN3Z3bmM3NVpXUHVNVkhEdDlMekh6bGgKblF4SjZEZ05LNHdhOURQRmdycXVrUEdLa0liZlRCMHZZanpxcks3amZPelk3WHpEYkZGNmVJdUxUMEVjQ0VESQo1K0dIZWV4TkdWRUlKYXhUT2Rwc0dkaUw3Wnkwa3hVY2xYMzNlTjAraE9OK2JXMXJIZHBRMWNxOVYxall1OWdQCnhwdXBFRlV6cU4rcFlncjdjaUkxa3k4MFR2SldRUG52VEoyQzUvbmdvbVVLTDJiTXpmSy8rWm1oODcxby95KzMKMW1tUkZFSlNMQTg1UlJBeERCYUN2bnloR2tGb1N0b0QrSkRSd0FRcndQTFkzYmFyWUw1dFRYamoyc1VLdFZ1bgpPRFhmQ3pLUGFtaExQVzYxSStjK1A4dkdBT2JQQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUVnZhdHMzR1UzV0wzR3RDVkJ1ZDlZMDFBSWxqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0x3LzJZMkpWdApvV2lQVFVBM3VuNmdzMVYxWGM0UjZaNEx1bmNVd0dKbTJmRFkwbGVDRk9PUEkvbS9HcStUV2pvMHRLTmlLeDNXClhZTWtkK1pMOHkvMy9TTm5qUjErbGRZbjNGT0NnSlJMbm96L3h0R0xRTVg1RTVvMDh6Q0xWdXE3OWVxLzU2VmcKN3pyemFmSmdQZGhWV3hPS3dFQ1JjZGJ4RnlKaUJQa0R2RitvclE0MW4vYktjMWFqU1JKVHZTNzdWNjB3KzFiUQppclF4WFVOc0toNEhPSjluZ0daYjhEWVo4RGxvQUxOc2Z3cmFXcmZRWHY1ZXJtUUdPMzZmQURLdE53KzVXQ2tiClFtNVlTdGR2WGVvSkQrdVp4RUFUTHk1Um1adEU1Yy81b0gwTmxuQWhreHhaT09RWHlrSVY0cDVOY2hzTTlvSWcKWDVPaVVqUUZlZks2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      insecure-skip-tls-verify: false
  - name: qa
    cluster:
      server: https://10.24.17.112:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRm9GL0l5WGFQZXd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeE1qY3hORFU1TURaYUZ3MHpOREV4TWpVeE5UQTBNRFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBZ05hQXRZa2F2a3UvU0JQZ3MwUk1MQmsyQnZVN295WDd5V1NuUXZiU1pJSUVjNVlNcys2d09JaTIKaVRXS2I3NHV4ZXhUN2VvQTRBdHdIa09ISXJJenpJZWxMRnZuMDB6Vk50OUpYMVhxbDltQUhJTHlueUp1M05yMQpES3huZXB5bTdXRzIyUEJ2cVoxL3MzWFduWlAzdURDcVdYZzNQMUJoMmEvcloxeWV5WDFTTEh4NW5qcFo5YWd4ClUvSmVzcXAxZE4rRTRmQzlnRTBDelFrUkI3U2FLWFVsR2hRMFRBN3pjbG1TbGlVVXNETTJnZjRacnY4TjJwR00KTUdEbjBiOVdlUzgwcnJCRmQwUnpxRVpKeE1qemRiR0FYZ2xWbDFaQ0ZrU1hjOE9kM1dSYTArR1JkR0RSZS81WQpUZWRLMVFyMi8yRk5FYVhIcUl5aVY2NTRwQ1ZsQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRT1RQYjNqVVNEUzdqaWlEWkVPeVl6bXBBTEZ6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWJjN1BNSTBjUwpKc3pyYnhXQkppNkNqdXhObUMrZ3ZPNGR3R2NtSVFwaHhsN1V1YkpseXl0UVl3UkRBRkN1d2JkRlp3U0dCTTMvCjRxUjNKS1E2cVdqL0g2M2FDVVYxNW1tL1JZdzhiVlpNNkVUVkF0VDdlRzJmS1FWeWFVQk9kamF2T3pxYWUwSmgKaHFFU0V2NVc5NnQ0KzF2SmpFNFZOVXErQW5GYldKdVZJODA1MEpWc3ljbGUrSmJYWlF6WHhhM1owMTRYWDFEUApZOEovbEQwalg1YXpINmZyemVnNC9nVVF6UE5lTlpkODZldlJiWVFQUUJnZCtZMWpQSG1ydEMwakdOZmdPUURTCmNtdHhpdFpWMXRVSkx2Wk9JNDJtNTBIeHhSZ2JzeThPRStOeHNSRDZGRm90c0VRUE1qR25HVDJsK0EvMGQwbFEKOVVZQjNCTDYxMDN6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      insecure-skip-tls-verify: false
  - name: pre
    cluster:
      server: https://10.24.17.70:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJU05tTHI4MTQxTEF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMU1UWXhOVE0xTVRKYUZ3MHpOREExTVRReE5UUXdNVEphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNySzEwU08xb3g3dzFLdHNVdE5lQlBvTjZocVRQS0ZnY2pqY1FBdnFLUGI0UHlhd1k4dmlXQ2l5SkQKSXE0VjFxR01iOFdnTDBWNzFjREQwRXJJSks3aFRVcjJXa0c2N0F3azZYdEx6VVBodEZYNHYwa05NcUk1QUJjaApiVVJ1ZXN2NGtwY3E3YWxUNVNqeWV2WW1scm8rOG1TK3VtbEt0bkt0eDNQN2JFSmhmdFNBWVNHeXE3MjZ3eUxOCmlpeTQ5YU02NWQ2WXdya1pzcDFjcndHT1FGR1hWRXJIMUpGRHMyaWxseHhHcHlJajBxVTgrTW5CZUpFd1RvMHIKR2RYbmFuSm1UZHAwUGVPVkJ6aWQwTkhoT2VuQWlXVXN1eDhrTnZOcUJ3SlhQSU1MN3V6VTBtRFVFVk9hdVlQQwo1VlNXOTB5eTBTRndqNkpXSkp1elVvQWxmaGVyQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUaFB0U1lwSWJUZzkwUGlVSlg2TURTK0loN1F6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjh5bUtjdUh1OAp3bG5hcWFKK1l3U3B0YmcwNkIyTWNHYU9VemRrMStrdlUwR1BPM0hvWU1ycTRoRFo1MlM5MlZDTmNxd0tZMklmCkYzb2tYQ2NpYjBJMVZDaEZxM0tTU0themgzLzlhRzNObmlEZVpHTGsyRVZHak9OcDhuNElYbHZxVVBaN3dFSkgKeStqRlZDYTZBa25DajRkaFpOUzBrMm5oaURmb1V6bE8xNjNpM1MzN3NSK0xnV0JEamRIYWdIN1FSTjV0MllJSQpkMVhXTCtLUUdYbm8yeDhPM1JFcy8rVjJRUysxWTVmUjZzZXhYSjRxcmI2REJndHB0Ni9sMk5uVjJPOWVRMDhOCjlENkFNYnExaVZMS1pnSzNMazZHSmR0RElVaW1qek5TeTZuS1d4SS84bFNTd2czWWJuYkZVTm9pMnkzaXRVQVUKK1dPaXh4RG9RSDBDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      insecure-skip-tls-verify: false
  - name: ecysap-itb
    cluster:
      server: https://10.24.17.67:6443
      insecure-skip-tls-verify: true
  - name: api-grp-prd-scmz-eus2-ocp-indramind-openshift-internal:6443
    cluster:
      server: https://api.grp-prd-scmz-eus2-ocp.indramind-openshift.internal:6443
      insecure-skip-tls-verify: true
  - name: rancher-desktop
    cluster:
      server: https://127.0.0.1:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RRMU16UTVNVGd3SGhjTk1qWXdOekl3TURjd09ETTRXaGNOTXpZd056RTNNRGN3T0RNNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RRMU16UTVNVGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSTnFRbkViZ2Z0bXJqdDNTS2hpSU04cE56MmFSU3Y2c3JPQWFtbnBFQ3IKTEpxQWdyZ09RdFZkOTNPR0RjNVdGMU44dUR4OXRyb1JVcFhJTVFvRGhKV2pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW5NL1V4L2tvSkE2QzJkM1FST0xMCnJuaXJ4bUF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU5aL2p5WDJXd2VPT2RVYzVRcWNCTnZUOEFtUU5aQXUKTm8zT1ozdk5mNnBXQWlCVE85KzNGV0YvRXJjOFdka2NJR1ovZ1FYVU11VWREVlVxZDZwdWY5MzlVUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      insecure-skip-tls-verify: false
users:
  - name: cyberdefense-oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://auth.cyberdefense.indra.es/realms/IC
          - --oidc-client-id=kubernetes
          - --oidc-client-secret=zw0sa06KxIE0Aghjqjdc37aL8gRtNYzx
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false
  - name: rancher-desktop
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJUHdaZURFT2RtREF3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemcwTlRNME9URTRNQjRYRFRJMk1EY3lNREEzTURnek9Gb1hEVEkzTURjeQpNREEzTURnek9Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPY0Jib25DdjVVd2ZCaUkKc3YvdE1IYm1Bc2IrbE9DbHZEbFJ1T1ZmQmVZaWduNHN3VnFsWTVoWVhXcVdBTFB4Q2lISCs5aEhxcTZQT1Z2MwpxQzR6cFZXalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVFN0SFY0b1gzRi9mQmd2VXlYKzViT0h0UmdSREFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQStkT2l6Ui9uLyswNHF2S3p3Z0VKNCt3UzRLblE3aG4xbDk3d3pWeHNua1lDSVFDWWVCMkVjcXc4NGdEKwpmSGNlT0pwV053QzB0VEZtWnVBYUZrZHVDaUswWEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZHpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM09EUTFNelE1TVRnd0hoY05Nall3TnpJd01EY3dPRE00V2hjTk16WXdOekUzTURjd09ETTQKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM09EUTFNelE1TVRnd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUWxSdHdTUTk2RUVHai9EUWlyZlBBWEpTZEo2YU1MWGZSR2RJTWNhM3NJCkthL1JLNHNjamk0NlRWaXM3c2NFYU1pU3pNT0dvak9hSDJhdGtubHhLKzVObzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUwclIxZUtGOXhmM3dZTDFNbC91Vwp6aDdVWUVRd0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ09tUW85UWY0RjJjMk9McGZSamZTN000OFQ3VllxWmMyClUyMTFhT0pFdHNJQ0lRQ1JSL0xUU29ZQWJEZ25WRURYVEFZblVvNnVEa0dVOUUwbWFYTCtmVWwxSEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxIKzI5SS8zU1RKSXVqWUVLbUVwMUFDeERwNlRDL1BPN01WWXROSm9mU0JvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNXdGdWljSy9sVEI4R0lpeS8rMHdkdVlDeHY2VTRLVzhPVkc0NVY4RjVpS0NmaXpCV3FWagptRmhkYXBZQXMvRUtJY2Y3MkVlcXJvODVXL2VvTGpPbFZRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  - name: rghernandez/api-grp-prd-scmz-eus2-ocp-indramind-openshift-internal:6443
    user:
      token: sha256~lamVBGw-GpSE72TR9GdEKPaZoO8H0Fd71p_p9L80eIY
contexts:
  - name: dev
    context:
      cluster: dev
      namespace: cyber-battle-lab
      user: cyberdefense-oidc
  - name: qa
    context:
      cluster: qa
      name: qa
      user: cyberdefense-oidc
  - name: pre
    context:
      cluster: pre
      name: pre
      user: cyberdefense-oidc
  - name: ecysap-itb
    context:
      cluster: ecysap-itb
      name: ecysap-itb
      user: cyberdefense-oidc
  - name: rancher-desktop
    context:
      cluster: rancher-desktop
      name: rancher-desktop
      user: rancher-desktop
  - name: pemncc-global-jemm-mediator
    context:
      cluster: api-grp-prd-scmz-eus2-ocp-indramind-openshift-internal:6443
      namespace: pemncc-global-jemm-mediator
      user: rghernandez/api-grp-prd-scmz-eus2-ocp-indramind-openshift-internal:6443
preferences: {}
current-context: dev
